import { useEffect, useState } from 'react';
import {
  AlertCircle, ArrowLeft, ArrowRight, Briefcase, CheckCircle2, FileText,
  GraduationCap, Loader2, MapPin, Save, ShieldCheck, Sparkles, Upload, UserRound,
} from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Textarea } from './ui/textarea';
import { Card } from './ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { JobCategory, JobSector } from '../types';
import { useAuth } from '../contexts/AuthContext';
import { extractJobTemplateFromPdf, JobTemplateExtractionResponse, JobTemplateVacancyExtraction } from '../api/jobTemplateExtraction';

interface JobPostingFormProps { onCancel: () => void; onSave: (jobData: JobFormData) => void; initialData?: Partial<JobFormData>; }
interface JobFormData {
  title: string; organization: string; sector: JobSector; category: JobCategory; location: string; state: string;
  qualification: string; experience: string; experienceLevel: 'entry' | 'mid' | 'senior' | 'executive'; speciality: string;
  dutyType: 'full_time' | 'part_time' | 'contract'; numberOfPosts?: number; salary: string; description: string; lastDate: string;
  requirements: string; benefits: string; contactEmail: string; contactPhone: string; pdfUrl?: string; applyLink?: string;
  pdfFile?: File; imageFile?: File; status?: string;
}

const jobCategories: JobCategory[] = ['Medical Officer','Junior Resident','Senior Resident','Specialist','Faculty','Dental','AYUSH','Nursing','Paramedical','Allied Health','Pharmacy','Psychology & Mental Health','Nutrition & Dietetics','Life Science & Research','Hospital Administration','Public Health'];
const INDIAN_STATES = ['Andaman and Nicobar Islands','Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chandigarh','Chhattisgarh','Dadra and Nagar Haveli and Daman and Diu','Delhi','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Ladakh','Lakshadweep','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Puducherry','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'];
const trim = (value?: string | null) => value?.trim() || '';

function inferCategory(value?: string | null): JobCategory {
  const t = trim(value).toLowerCase();
  if (/junior resident/.test(t)) return 'Junior Resident'; if (/senior resident/.test(t)) return 'Senior Resident';
  if (/medical officer|gdm[o]?/.test(t)) return 'Medical Officer'; if (/professor|faculty|lecturer|tutor/.test(t)) return 'Faculty';
  if (/specialist|consultant/.test(t)) return 'Specialist'; if (/dental|dentist|bds|mds/.test(t)) return 'Dental';
  if (/ayush|bams|bhms|unani|ayurveda/.test(t)) return 'AYUSH'; if (/nurs/.test(t)) return 'Nursing'; if (/pharmac/.test(t)) return 'Pharmacy';
  if (/psych/.test(t)) return 'Psychology & Mental Health'; if (/nutrition|diet/.test(t)) return 'Nutrition & Dietetics';
  if (/public health|epidemi/.test(t)) return 'Public Health'; if (/administration|administrator/.test(t)) return 'Hospital Administration';
  if (/research|scientist|life science/.test(t)) return 'Life Science & Research'; if (/technician|technologist|paramedic/.test(t)) return 'Paramedical';
  return 'Medical Officer';
}
function inferDutyType(value?: string | null): JobFormData['dutyType'] { const t=trim(value).toLowerCase(); return /part[ -]?time/.test(t)?'part_time':/contract|temporary|fixed term|tenure|walk[- ]?in/.test(t)?'contract':'full_time'; }
function inferState(location?: string | null) { const t=trim(location).toLowerCase(); return INDIAN_STATES.find((state)=>t.includes(state.toLowerCase())) || ''; }
function locationWithState(location:string,state:string){ const l=location.trim(),s=state.trim(); return !s||l.toLowerCase().includes(s.toLowerCase())?l:l?`${l}, ${s}`:s; }

function formatExtractedDescription(extraction: JobTemplateExtractionResponse, vacancy?: JobTemplateVacancyExtraction) {
  const r=extraction.recruitment||{}; const lines:string[]=[];
  const add=(h:string,values:string[])=>{const p=values.filter(Boolean);if(!p.length)return;if(lines.length)lines.push('');lines.push(h,'',...p);};
  add('JOB DETAILS',[trim(vacancy?.postName||r.title)&&`Post: ${trim(vacancy?.postName||r.title)}`,trim(r.organisationName)&&`Organisation: ${trim(r.organisationName)}`,trim(vacancy?.department)&&`Department: ${trim(vacancy?.department)}`,trim(vacancy?.speciality)&&`Speciality: ${trim(vacancy?.speciality)}`,trim(vacancy?.location||r.location)&&`Location: ${trim(vacancy?.location||r.location)}`,vacancy?.numberOfVacancies?`Number of Posts: ${vacancy.numberOfVacancies}`:'',trim(vacancy?.jobType)&&`Job Type: ${trim(vacancy?.jobType)}`]);
  add('ELIGIBILITY',[trim(vacancy?.qualification)&&`Qualification: ${trim(vacancy?.qualification)}`,trim(vacancy?.experience)&&`Experience: ${trim(vacancy?.experience)}`,trim(vacancy?.ageLimit)&&`Age Limit: ${trim(vacancy?.ageLimit)}`,trim(vacancy?.otherEligibilityRequirements)]);
  add('PAY / SALARY',[trim(vacancy?.salary||vacancy?.payScale||vacancy?.payLevel)]);
  add('APPLICATION DETAILS',[trim(r.applicationStartDate)&&`Application Start Date: ${trim(r.applicationStartDate)}`,trim(r.applicationLastDate)&&`Last Date to Apply: ${trim(r.applicationLastDate)}`,trim(r.applicationFee)&&`Application Fee: ${trim(r.applicationFee)}`,trim(r.selectionProcess)&&`Selection Process: ${trim(r.selectionProcess)}`]);
  add('OFFICIAL LINKS',[trim(r.officialWebsite)&&`Official Website: ${trim(r.officialWebsite)}`,trim(r.officialNotificationUrl)&&`Notification PDF / Notice: ${trim(r.officialNotificationUrl)}`,trim(r.officialApplicationUrl)&&`Apply Link (if online): ${trim(r.officialApplicationUrl)}`,extraction.sourcePdfName?`Attached Notification: ${extraction.sourcePdfName}`:'']);
  add('IMPORTANT INSTRUCTIONS',[trim(r.importantInstructions)]); return lines.join('\n').trim();
}

const defaultData:JobFormData={title:'',organization:'',sector:'private',category:'Medical Officer',location:'',state:'',qualification:'',experience:'',experienceLevel:'entry',speciality:'',dutyType:'full_time',numberOfPosts:undefined,salary:'',description:'',lastDate:'',requirements:'',benefits:'',contactEmail:'',contactPhone:'',applyLink:''};

export function JobPostingForm({onCancel,onSave,initialData}:JobPostingFormProps){
  const {user}=useAuth(); const isEmployer=user?.role==='employer'; const isAdmin=user?.role==='admin';
  const [step,setStep]=useState(1); const [formData,setFormData]=useState<JobFormData>(defaultData); const [extractingPdf,setExtractingPdf]=useState(false);
  const [pdfMessage,setPdfMessage]=useState(''); const [pdfError,setPdfError]=useState(''); const [pdfExtraction,setPdfExtraction]=useState<JobTemplateExtractionResponse|null>(null); const [selectedVacancyIndex,setSelectedVacancyIndex]=useState(0);
  useEffect(()=>{if(!initialData)return;setFormData((p)=>{const m={...p,...initialData} as JobFormData;return{...m,state:initialData.state||inferState(initialData.location),sector:isEmployer?'private':(m.sector||'private')}});},[initialData,isEmployer]);
  useEffect(()=>{if(isEmployer&&formData.sector!=='private')setFormData((p)=>({...p,sector:'private'}));},[isEmployer,formData.sector]);
  const setField=<K extends keyof JobFormData>(field:K,value:JobFormData[K])=>setFormData((p)=>({...p,[field]:value}));
  const progress=(step/4)*100; const stepValid=step===1?Boolean(formData.title.trim()&&formData.organization.trim()&&formData.location.trim()&&formData.state.trim()):step===3?Boolean(formData.description.trim()&&formData.lastDate):true;

  const applyExtractedVacancy=(extraction:JobTemplateExtractionResponse,index:number)=>{const vacancies=extraction.vacancies||[];const v=vacancies[index];const r=extraction.recruitment||{};const location=trim(v?.location)||trim(r.location);const title=trim(v?.postName)||trim(r.title);const posts=v?.numberOfVacancies&&v.numberOfVacancies>0?v.numberOfVacancies:vacancies.length<=1&&r.totalVacancies&&r.totalVacancies>0?r.totalVacancies:undefined;setSelectedVacancyIndex(index);setFormData((p)=>({...p,title:title||p.title,organization:trim(r.organisationName)||p.organization,sector:isEmployer?'private':(r.sector==='government'||r.sector==='private'?r.sector:p.sector),category:inferCategory(title||v?.department||p.title),location,state:inferState(location)||p.state,qualification:trim(v?.qualification),experience:trim(v?.experience),speciality:trim(v?.speciality||v?.department),dutyType:inferDutyType(v?.jobType),numberOfPosts:posts,salary:trim(v?.salary||v?.payScale||v?.payLevel),lastDate:trim(r.applicationLastDate),requirements:trim(v?.otherEligibilityRequirements),applyLink:trim(r.officialApplicationUrl)||p.applyLink,description:formatExtractedDescription(extraction,v)||p.description}));};
  const handlePdf=async(file?:File)=>{setField('pdfFile',file);setPdfError('');setPdfMessage('');setPdfExtraction(null);setSelectedVacancyIndex(0);if(!file)return;if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf')){setPdfError('Please select a PDF file.');return;}setExtractingPdf(true);try{const extraction=await extractJobTemplateFromPdf(file);setPdfExtraction(extraction);applyExtractedVacancy(extraction,0);const count=extraction.vacancies?.length||0;setPdfMessage(count>1?`${count} vacancy rows extracted with Gemini. Select the vacancy you want to post.`:'Gemini extraction completed. Review the highlighted fields before saving.');}catch(error:any){setPdfError(error?.response?.data?.error||error?.response?.data?.message||'Unable to extract this PDF. You can still complete the form manually.');}finally{setExtractingPdf(false);}};
  const save=(status?:string)=>onSave({...formData,sector:isEmployer?'private':formData.sector,location:locationWithState(formData.location,formData.state),status});

  return <div className="mx-auto max-w-5xl space-y-5"><Card className="overflow-hidden border-slate-200 shadow-sm">
    <div className="bg-gradient-to-r from-blue-700 via-blue-600 to-indigo-600 px-5 py-5 text-white sm:px-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles className="h-5 w-5"/><h1 className="text-xl font-semibold">Job Template</h1></div><p className="mt-1 text-sm text-blue-100">State-ready filters, clear colour sections and Gemini PDF auto-fill.</p></div><Badge className="border-white/25 bg-white/15 text-white hover:bg-white/15">{isEmployer?'Employer · Private Jobs Only':isAdmin?'Admin · Govt + Private':'Job Editor'}</Badge></div><Progress value={progress} className="mt-5 h-2 bg-white/20"/><div className="mt-3 grid grid-cols-4 gap-2 text-center text-xs text-blue-100">{['Job & Location','Eligibility','Description','Contact'].map((label,index)=><span key={label} className={step===index+1?'font-semibold text-white':''}>{index+1}. {label}</span>)}</div></div>
    <div className="p-4 sm:p-7">
      {step===1&&<div className="space-y-5"><SectionTitle icon={Briefcase} title="Post & Organisation" subtitle="Core vacancy identity" tone="blue"/>
        <Card className="border-indigo-200 bg-indigo-50/60 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="rounded-xl bg-indigo-100 p-2 text-indigo-700"><Upload className="h-5 w-5"/></div><div><p className="font-semibold text-slate-900">Gemini PDF Auto-Fill</p><p className="text-xs text-slate-600">Upload the official notice and review the extracted values.</p></div></div><label className="inline-flex cursor-pointer items-center justify-center rounded-lg border border-indigo-200 bg-white px-4 py-2 text-sm font-medium text-indigo-700 hover:bg-indigo-50">{extractingPdf?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<FileText className="mr-2 h-4 w-4"/>}{extractingPdf?'Reading PDF…':formData.pdfFile?'Change PDF':'Choose PDF'}<input type="file" accept="application/pdf,.pdf" className="sr-only" disabled={extractingPdf} onChange={(e)=>void handlePdf(e.target.files?.[0])}/></label></div>{extractingPdf&&<div className="mt-4 rounded-lg border border-indigo-100 bg-white p-3"><div className="flex items-center gap-2 text-sm font-medium text-indigo-700"><Loader2 className="h-4 w-4 animate-spin"/>Extracting post, qualification, location and dates with Gemini…</div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-indigo-100"><div className="h-full w-2/3 animate-pulse rounded-full bg-indigo-500"/></div></div>}{pdfMessage&&<Message tone="success" text={pdfMessage}/>} {pdfError&&<Message tone="error" text={pdfError}/>} {(pdfExtraction?.vacancies?.length||0)>1&&<div className="mt-3"><Label>Vacancy to Autofill</Label><Select value={String(selectedVacancyIndex)} onValueChange={(value)=>applyExtractedVacancy(pdfExtraction!,Number(value))}><SelectTrigger className="mt-1 bg-white"><SelectValue/></SelectTrigger><SelectContent>{pdfExtraction!.vacancies!.map((v,index)=><SelectItem key={`${v.postName}-${index}`} value={String(index)}>{v.postName||`Vacancy ${index+1}`}{v.department?` — ${v.department}`:''}{v.numberOfVacancies?` (${v.numberOfVacancies})`:''}</SelectItem>)}</SelectContent></Select></div>}</Card>
        <div className="grid gap-4 md:grid-cols-2"><Field className="md:col-span-2" label="Post / Job Title *" accent="blue"><Input value={formData.title} onChange={(e)=>setField('title',e.target.value)} placeholder="e.g. Senior Resident"/></Field><Field className="md:col-span-2" label="Organisation / Hospital *" accent="blue"><Input value={formData.organization} onChange={(e)=>setField('organization',e.target.value)} placeholder="e.g. AIIMS Gorakhpur"/></Field><Field label="Job Sector" accent="violet">{isEmployer?<div className="flex h-10 items-center gap-2 rounded-md border border-emerald-200 bg-emerald-50 px-3 text-sm font-medium text-emerald-800"><ShieldCheck className="h-4 w-4"/>Private <span className="ml-auto text-xs font-normal text-emerald-600">Govt is Admin-only</span></div>:<Select value={formData.sector} onValueChange={(value:JobSector)=>setField('sector',value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="private">Private</SelectItem><SelectItem value="government">Government</SelectItem></SelectContent></Select>}</Field><Field label="Job Role / Category" accent="violet"><Select value={formData.category} onValueChange={(value:JobCategory)=>setField('category',value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{jobCategories.map((category)=><SelectItem key={category} value={category}>{category}</SelectItem>)}</SelectContent></Select></Field></div>
        <SectionTitle icon={MapPin} title="Location" subtitle="State is explicit so filtering stays consistent." tone="emerald"/><div className="grid gap-4 md:grid-cols-2"><Field label="City / Place *" accent="emerald"><Input value={formData.location} onChange={(e)=>{setField('location',e.target.value);if(!formData.state){const detected=inferState(e.target.value);if(detected)setField('state',detected);}}} placeholder="e.g. Gorakhpur"/></Field><Field label="State *" accent="emerald"><Select value={formData.state} onValueChange={(value)=>setField('state',value)}><SelectTrigger><SelectValue placeholder="Select state"/></SelectTrigger><SelectContent>{INDIAN_STATES.map((state)=><SelectItem key={state} value={state}>{state}</SelectItem>)}</SelectContent></Select></Field></div>
      </div>}
      {step===2&&<div className="space-y-5"><SectionTitle icon={GraduationCap} title="Eligibility & Vacancy Details" subtitle="Purple = qualification, green = vacancy, amber = salary." tone="violet"/><div className="grid gap-4 md:grid-cols-2"><Field className="md:col-span-2" label="Qualification" accent="violet"><Input value={formData.qualification} onChange={(e)=>setField('qualification',e.target.value)} placeholder="e.g. MD/MS/DNB"/></Field><Field label="Experience" accent="violet"><Input value={formData.experience} onChange={(e)=>setField('experience',e.target.value)}/></Field><Field label="Experience Level" accent="violet"><Select value={formData.experienceLevel} onValueChange={(value:JobFormData['experienceLevel'])=>setField('experienceLevel',value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="entry">Entry Level</SelectItem><SelectItem value="mid">Mid Level</SelectItem><SelectItem value="senior">Senior Level</SelectItem><SelectItem value="executive">Executive Level</SelectItem></SelectContent></Select></Field><Field label="Speciality / Department" accent="violet"><Input value={formData.speciality} onChange={(e)=>setField('speciality',e.target.value)}/></Field><Field label="Employment Type" accent="blue"><Select value={formData.dutyType} onValueChange={(value:JobFormData['dutyType'])=>setField('dutyType',value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="full_time">Full Time</SelectItem><SelectItem value="part_time">Part Time</SelectItem><SelectItem value="contract">Contract</SelectItem></SelectContent></Select></Field><Field label="Number of Posts" accent="emerald"><Input type="number" min="1" value={formData.numberOfPosts??''} onChange={(e)=>setField('numberOfPosts',e.target.value?Number(e.target.value):undefined)}/></Field><Field label="Salary / Pay" accent="amber"><Input value={formData.salary} onChange={(e)=>setField('salary',e.target.value)}/></Field><Field className="md:col-span-2" label="Additional Eligibility" accent="violet"><Textarea rows={3} value={formData.requirements} onChange={(e)=>setField('requirements',e.target.value)}/></Field><Field className="md:col-span-2" label="Benefits" accent="emerald"><Textarea rows={2} value={formData.benefits} onChange={(e)=>setField('benefits',e.target.value)}/></Field></div></div>}
      {step===3&&<div className="space-y-5"><SectionTitle icon={FileText} title="Job Description & Application" subtitle={formData.sector==='government'?'Government applications may be online, offline or direct.':'Private candidates apply through MedExJob.'} tone="blue"/>{formData.sector==='government'&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Government job checklist:</strong> include official website, notification PDF, and an Apply Link only when the notice actually provides an online route.</div>}<Field label="Job Description *" accent="blue"><Textarea rows={10} value={formData.description} onChange={(e)=>setField('description',e.target.value)} placeholder="Role details, eligibility, application method and official links..."/></Field><div className="grid gap-4 md:grid-cols-2"><Field label="Last Date *" accent="rose"><Input type="date" value={formData.lastDate} onChange={(e)=>setField('lastDate',e.target.value)}/></Field><Field label={formData.sector==='government'?'Official Apply Link (only if online)':'External Apply Link (optional)'} accent="blue"><Input value={formData.applyLink||''} onChange={(e)=>setField('applyLink',e.target.value)} placeholder="https://..."/></Field></div></div>}
      {step===4&&<div className="space-y-5"><SectionTitle icon={UserRound} title="Contact & Attachments" subtitle="Optional contact details and supporting files." tone="emerald"/><div className="grid gap-4 md:grid-cols-2"><Field label="Contact Email" accent="emerald"><Input type="email" value={formData.contactEmail} onChange={(e)=>setField('contactEmail',e.target.value)}/></Field><Field label="Contact Phone" accent="emerald"><Input value={formData.contactPhone} onChange={(e)=>setField('contactPhone',e.target.value)}/></Field><Field className="md:col-span-2" label="Job Image" accent="blue"><Input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>setField('imageFile',e.target.files?.[0])}/></Field></div><Card className="border-slate-200 bg-slate-50 p-4 text-sm text-slate-700"><div className="grid gap-2 sm:grid-cols-2"><span><strong>Post:</strong> {formData.title||'—'}</span><span><strong>Sector:</strong> {isEmployer?'Private':formData.sector}</span><span><strong>Location:</strong> {locationWithState(formData.location,formData.state)||'—'}</span><span><strong>Posts:</strong> {formData.numberOfPosts||'Not specified'}</span></div></Card></div>}
    </div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t bg-slate-50 px-4 py-4 sm:px-7"><div><Button variant="ghost" onClick={onCancel}>Cancel</Button>{step>1&&<Button variant="outline" className="ml-2" onClick={()=>setStep((v)=>v-1)}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button>}</div><div className="flex gap-2">{step===4&&<Button variant="outline" onClick={()=>save('draft')}><Save className="mr-2 h-4 w-4"/>Save Draft</Button>}{step<4?<Button disabled={!stepValid} onClick={()=>setStep((v)=>v+1)}>Continue<ArrowRight className="ml-2 h-4 w-4"/></Button>:<Button onClick={()=>save()}><CheckCircle2 className="mr-2 h-4 w-4"/>{initialData?'Update Job':'Post Job'}</Button>}</div></div>
  </Card></div>;
}

function SectionTitle({icon:Icon,title,subtitle,tone}:{icon:any;title:string;subtitle:string;tone:'blue'|'violet'|'emerald'}){const styles=tone==='violet'?'border-violet-200 bg-violet-50 text-violet-800':tone==='emerald'?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-blue-200 bg-blue-50 text-blue-800';return <div className={`flex items-start gap-3 rounded-xl border p-3 ${styles}`}><Icon className="mt-0.5 h-5 w-5 shrink-0"/><div><h2 className="font-semibold">{title}</h2><p className="mt-0.5 text-xs opacity-80">{subtitle}</p></div></div>;}
function Field({label,children,className='',accent='slate'}:{label:string;children:React.ReactNode;className?:string;accent?:'blue'|'violet'|'emerald'|'amber'|'rose'|'slate'}){const border=accent==='violet'?'border-l-violet-400':accent==='emerald'?'border-l-emerald-400':accent==='amber'?'border-l-amber-400':accent==='rose'?'border-l-rose-400':accent==='blue'?'border-l-blue-400':'border-l-slate-300';return <div className={`rounded-lg border border-slate-200 border-l-4 bg-white p-3 ${border} ${className}`}><Label className="mb-2 block text-sm font-medium text-slate-800">{label}</Label>{children}</div>;}
function Message({tone,text}:{tone:'success'|'error';text:string}){const success=tone==='success';return <div className={`mt-3 flex items-start gap-2 rounded-lg px-3 py-2 text-xs ${success?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-700'}`}>{success?<CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0"/>:<AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/>}<span>{text}</span></div>;}
