import type { Recruitment } from '../api/recruitments';

export const TEST_FACULTY_RECRUITMENT: Recruitment = {
  id: 'test-faculty-recruitment',
  slug: 'test-faculty-recruitment',
  title: 'Professor, Associate Professor, Assistant Professor Recruitment 2026 - Multiple Departments',
  organisationName: 'AIIMS New Delhi',
  sector: 'government',
  location: 'New Delhi (Ansari Nagar), Delhi',
  totalVacancies: 38,
  applicationStartDate: '2026-09-01',
  applicationLastDate: '2026-10-31',
  applicationFee: 'Rs 1500 (Gen/OBC), Rs 1200 (SC/ST/EWS), PwBD: Exempt',
  selectionProcess: 'Screening of applications followed by interview by the Standing Selection Committee of AIIMS New Delhi',
  officialNotificationUrl: 'https://aiims.edu/recruitment/faculty-2026.pdf',
  officialApplicationUrl: 'https://aiims.edu/apply',
  officialWebsite: 'https://aiims.edu',
  importantInstructions:
    'Candidates must possess recognized PG qualification (MD/MS/DNB/M.Ch/DM) with required teaching/clinical experience as per NMC/AIIMS norms. Age relaxation as per Govt of India rules.',
  jobDescription: `### Faculty Recruitment 2026 - All India Institute of Medical Sciences (AIIMS), New Delhi

Applications are invited from Indian citizens and Overseas Citizens of India for direct recruitment to the following regular faculty posts across multiple departments.

| Department | Professor | Associate Professor | Assistant Professor | Total |
| --- | --- | --- | --- | --- |
| Cardiology | 2 | 2 | 3 | 7 |
| Neurology | 1 | 2 | 3 | 6 |
| Anaesthesiology | 2 | 3 | 4 | 9 |
| Paediatrics | 1 | 2 | 2 | 5 |
| Radiodiagnosis | 1 | 2 | 3 | 6 |
| Orthopaedics | 1 | 1 | 3 | 5 |

**Total Vacancies: 38 Across 6 Medical Specialties**

**Pay Scales & Allowances:**
- **Professor:** Level-14A (Rs 1,68,900 - 2,20,400) + NPA
- **Associate Professor:** Level-13A2 (Rs 1,48,200 - 2,11,400) + NPA
- **Assistant Professor:** Level-12 (Rs 1,01,500 - 1,67,400) + NPA
`,
  officialSourceVerified: true,
  status: 'PUBLISHED',
  vacancies: [
    {
      id: 'test-vac-1',
      postName: 'Professor, Associate Professor, Assistant Professor',
      department: 'Cardiology',
      speciality: 'Cardiology',
      numberOfVacancies: 7,
      category: 'UR (3), OBC (2), SC (1), EWS (1)',
      qualification: 'DM or DNB in Cardiology with valid NMC/State Council registration',
      experience: '1-14 years teaching/research experience depending on cadre',
      salary: 'Rs 1,01,500 - 2,20,400/month + NPA',
      payLevel: 'Level 12 to 14A',
      payScale: 'PB-4 with AGP Rs 8,000 to 10,500',
      jobType: 'Full Time',
      location: 'New Delhi, Delhi',
      publishedJobId: 'test-job-cardiology',
      lastDate: '2026-10-31',
      status: 'PUBLISHED',
      otherEligibilityRequirements: 'Must have active publications in indexed journals as per NMC guidelines.',
    },
    {
      id: 'test-vac-2',
      postName: 'Professor, Associate Professor, Assistant Professor',
      department: 'Neurology',
      speciality: 'Neurology',
      numberOfVacancies: 6,
      category: 'UR (2), OBC (2), ST (1), EWS (1)',
      qualification: 'DM or DNB in Neurology with valid NMC/State Council registration',
      experience: '1-14 years teaching/research experience depending on cadre',
      salary: 'Rs 1,01,500 - 2,20,400/month + NPA',
      payLevel: 'Level 12 to 14A',
      payScale: 'PB-4 with AGP Rs 8,000 to 10,500',
      jobType: 'Full Time',
      location: 'New Delhi, Delhi',
      publishedJobId: 'test-job-neurology',
      lastDate: '2026-10-31',
      status: 'PUBLISHED',
      otherEligibilityRequirements: 'Specialization in stroke or electrophysiology preferred.',
    },
    {
      id: 'test-vac-3',
      postName: 'Professor, Associate Professor, Assistant Professor',
      department: 'Anaesthesiology',
      speciality: 'Anaesthesiology',
      numberOfVacancies: 9,
      category: 'UR (4), OBC (2), SC (2), EWS (1)',
      qualification: 'MD or DNB in Anaesthesiology with valid NMC/State Council registration',
      experience: '1-14 years teaching/research experience depending on cadre',
      salary: 'Rs 1,01,500 - 2,20,400/month + NPA',
      payLevel: 'Level 12 to 14A',
      payScale: 'PB-4 with AGP Rs 8,000 to 10,500',
      jobType: 'Full Time',
      location: 'New Delhi, Delhi',
      publishedJobId: 'test-job-anaesthesiology',
      lastDate: '2026-10-31',
      status: 'PUBLISHED',
      otherEligibilityRequirements: 'Experience in cardiac, neuro, or transplant anaesthesia preferred.',
    },
    {
      id: 'test-vac-4',
      postName: 'Professor, Associate Professor, Assistant Professor',
      department: 'Paediatrics',
      speciality: 'Paediatrics',
      numberOfVacancies: 5,
      category: 'UR (2), OBC (1), SC (1), EWS (1)',
      qualification: 'MD or DNB in Paediatrics with valid NMC/State Council registration',
      experience: '1-14 years teaching/research experience depending on cadre',
      salary: 'Rs 1,01,500 - 2,20,400/month + NPA',
      payLevel: 'Level 12 to 14A',
      payScale: 'PB-4 with AGP Rs 8,000 to 10,500',
      jobType: 'Full Time',
      location: 'New Delhi, Delhi',
      publishedJobId: 'test-job-paediatrics',
      lastDate: '2026-10-31',
      status: 'PUBLISHED',
      otherEligibilityRequirements: 'Neonatology or paediatric critical care exposure preferred.',
    },
    {
      id: 'test-vac-5',
      postName: 'Professor, Associate Professor, Assistant Professor',
      department: 'Radiodiagnosis',
      speciality: 'Radiodiagnosis',
      numberOfVacancies: 6,
      category: 'UR (3), OBC (1), SC (1), ST (1)',
      qualification: 'MD or DNB in Radiodiagnosis with valid NMC/State Council registration',
      experience: '1-14 years teaching/research experience depending on cadre',
      salary: 'Rs 1,01,500 - 2,20,400/month + NPA',
      payLevel: 'Level 12 to 14A',
      payScale: 'PB-4 with AGP Rs 8,000 to 10,500',
      jobType: 'Full Time',
      location: 'New Delhi, Delhi',
      publishedJobId: 'test-job-radiodiagnosis',
      lastDate: '2026-10-31',
      status: 'PUBLISHED',
      otherEligibilityRequirements: 'Competence in MRI/CT reporting and interventional radiology.',
    },
    {
      id: 'test-vac-6',
      postName: 'Professor, Associate Professor, Assistant Professor',
      department: 'Orthopaedics',
      speciality: 'Orthopaedics',
      numberOfVacancies: 5,
      category: 'UR (2), OBC (1), SC (1), EWS (1)',
      qualification: 'MS or DNB in Orthopaedics with valid NMC/State Council registration',
      experience: '1-14 years teaching/research experience depending on cadre',
      salary: 'Rs 1,01,500 - 2,20,400/month + NPA',
      payLevel: 'Level 12 to 14A',
      payScale: 'PB-4 with AGP Rs 8,000 to 10,500',
      jobType: 'Full Time',
      location: 'New Delhi, Delhi',
      publishedJobId: 'test-job-orthopaedics',
      lastDate: '2026-10-31',
      status: 'PUBLISHED',
      otherEligibilityRequirements: 'Experience in arthroplasty, spine, or pediatric orthopaedics.',
    },
  ],
};

export const TEST_FACULTY_JOB = {
  id: 'test-faculty-recruitment',
  title: 'Professor, Associate Professor, Assistant Professor Recruitment 2026 - Multiple Departments',
  organization: 'AIIMS New Delhi',
  companyName: 'AIIMS New Delhi',
  sector: 'government',
  category: 'Faculty',
  location: 'New Delhi (Ansari Nagar), Delhi',
  numberOfPosts: 38,
  qualification: 'MD / MS / DNB / DM / M.Ch in relevant medical specialty',
  experience: '1 to 14 years teaching/clinical experience as per NMC norms',
  salary: 'Rs 1,01,500 - 2,20,400 per month (Level 12 to 14A)',
  lastDate: '2026-10-31',
  postedDate: '2026-09-01',
  applyLink: 'https://aiims.edu/apply',
  jobDocumentUrl: 'https://aiims.edu/recruitment/faculty-2026.pdf',
  pdfUrl: 'https://aiims.edu/recruitment/faculty-2026.pdf',
  officialWebsite: 'https://aiims.edu',
  sourceRecruitmentId: 'test-faculty-recruitment',
  sourceRecruitment: TEST_FACULTY_RECRUITMENT,
  description: TEST_FACULTY_RECRUITMENT.jobDescription,
  requirements: TEST_FACULTY_RECRUITMENT.importantInstructions,
  selectionProcess: TEST_FACULTY_RECRUITMENT.selectionProcess,
  status: 'active',
  featured: true,
  isFeatured: true,
};
